version: '3'

services:

  flaskapp:
    build: ./pythonApp
    image: flask_gunicorn:latest
    container_name: flaskapp

  nginx:
    build: ./nginx
    image: nginxnew:latest
    container_name: nginx
    environment:
      - SERVER_NAME=0.0.0.0
    ports:
      - "80:80"
    restart: always

networks:
  default:
    driver: bridge
